server:
  port: 8082
  tomcat:
    threads:
      max: 50
    accept-count: 50
    max-connections: 100
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

hm:
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
  db:
    database: hm-cart

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 #sentinel控制台地址
      http-method-specify: true # 是否设置请求方式作为资源名称
